import mongoose, { isObjectIdOrHexString } from "mongoose"

const Schema = mongoose.Schema

let CharacterSchema = new Schema({
    fullName: String,
    aliases: String,
    gender: String,
    occupation: [String],
    family: [String],
    dateOfBirth: String,
    actor: String,
    picture: String
})

export default mongoose.model("Character", CharacterSchema)




let UserSchema = new Schema ({
    fullName: {type: String, required: true},
    emailAddress: {type: String, required: true},
    password_digest: {type: String, required: true},
        // userID: autogenerated

})

let EventSchema = new Schema ({
    eventName: {type: String, required: true},
    eventDate: {type: String, required: true},
    eventTime: {type: String, required: true},
    eventVenue: {type: String, required: true},
    eventPrice: {type: String, required: true},
    eventCity: {type: String, required: true},
    eventTickets: {type: String, required: true},
    eventPicture: {type: String, required: true},
    eventCategory: {type: String, requied: true},
    // eventID: autogenerated
}) 

let FavSchema = new Schema ({
    userID: {type: Schema.Types.ObjectId, ref: "users"},
    eventID: {type: Schema.Types.ObjectId, ref: "events"},
    isFavorited: { type: Boolean}
})