# Generated by Django 5.0.3 on 2024-04-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civ',
            name='name',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='civ',
            name='subject',
            field=models.CharField(choices=[('Franks', 'Franks'), ('Goths', 'Goths'), ('Huns', 'Huns')], max_length=12),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
